name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build-linux
      run: npm run electron-package
    -name: build-mac
      run: npm run make-mac
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

