name: Build
on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
      env:
        CI: false
    - name: package
      continue-on-error: true
      run: npm run electron-package-linux

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
      env:
        CI: false
    - name: package
      continue-on-error: true
      run: npm run electron-package-mac
  
  package:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac]
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
