name: Build
on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
      env:
        CI: false
    - name: package
      continue-on-error: true
      run: npm run electron-package-linux
    - uses: actions/upload-artifact@v2
      with:
        name: linux-package
        path: out/Artemisgcp-*.AppImage
    

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build
      env:
        CI: false
    - name: package
      continue-on-error: true
      run: npm run electron-package-mac
    - uses: actions/upload-artifact@v2
      with:
        name: mac-package
        path: out/Artemisgcp-*.dmg
  
  package:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - uses: actions/download-artifact@v2
      with:
        name: linux-package
    - uses: actions/download-artifact@v2
      with:
        name: mac-package
    - name: see directory
      run: ls
    - name: install dependencies
      run: npm install
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
